import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FloatingNav } from "@/components/ui/floating-navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navItems = [
    {
      name: "About",
      link: "/",
    },
    {
      name: "Projects",
      link: "/projects",
    },
   
    {
      name: "Experiences",
      link: "/experiences",
    },
  ];
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen  flex-col items-center bg-[#ffff] justify-between p-24">
          <FloatingNav navItems={navItems} />
        {children}
        </main>
      </body>
    </html>
  );
}
